// <auto-generated>
// Rewired Constants
// This list was generated on 1/23/2021 5:15:51 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Physical
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Move Horizontal")]
        public const int Move_Horizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Move Vertical")]
        public const int Move_Vertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Look Horizontal")]
        public const int Look_Horizontal = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Look Vertical")]
        public const int Look_Vertical = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Emit Scan")]
        public const int Scan = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Equip Scanner 1")]
        public const int Scanner1 = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Equip Scanner 2")]
        public const int Scanner2 = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Equip Scanner 3")]
        public const int Scanner3 = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Equip Next Scanner")]
        public const int NextScanner = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Jump")]
        public const int Jump = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Movement, Looking, and Physical Interactions", friendlyName = "Start talking to an NPC")]
        public const int Talk = 7;
        // Menu
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player Menu, Start Menu, and UI Interactions", friendlyName = "Toggle Player Menu")]
        public const int PlayerMenu = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player Menu, Start Menu, and UI Interactions", friendlyName = "Toggle Start Menu")]
        public const int StartMenu = 4;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player Zero")]
        public const int P0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
